---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004: false # Unordered list style
MD007:
  indent: 2 # Unordered list indentation
# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md013.md
MD013:
  # Number of characters
  line_length: 800
  # Number of characters for headings
  heading_line_length: 100
  # Number of characters for code blocks
  code_block_line_length: 800
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false
MD026:
  punctuation: ".,;:!。，；:" # List of not allowed
MD029: false # Ordered list item prefix
MD033: false # Allow inline HTML
MD036: false # Emphasis used instead of a heading
MD053: false # Super Linter broke this in v4.9.5

#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
